<?php

/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$product    = $block->getProduct();
$attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($product->isSaleable() && count($attributes)):?>
    <?php foreach ($attributes as $attribute): ?>
        <div class="field configurable required">
            <label class="label" for="attribute<?php /* @escapeNotVerified */ echo $attribute->getAttributeId() ?>">
                <span><?php echo $block->escapeHtml($attribute->getProductAttribute()->getStoreLabel()) ?></span>
            </label>
            <div class="control">
                <select name="super_attribute[<?php /* @escapeNotVerified */ echo $attribute->getAttributeId() ?>]"
					data-validate="{required:true}" id="attribute<?php /* @escapeNotVerified */ echo $attribute->getAttributeId() ?>" class="super-attribute-select">
                    <option value=""><?php /* @escapeNotVerified */ echo __('Choose an Option...') ?></option>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "quickConfigurable": {
                    "spConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>,
					"priceHolderSelector": "#cboxContent div[data-product-id=<?php echo $product->getId() ?>]",
					"productId":<?php /* @escapeNotVerified */  echo $product->getId() ?>
                }
            }
        }
    </script>
<?php endif;?>
